Repository NITKC-DEV/Kisarazu-Multi-Manager, pull requests merged in 2023-04, with the labels that each got.

#21 寮食切り替え通知ON/OFF実装
  botmain.js
  commands/general.js
  functions/ryoshoku.js
Labels: feature

#22 SelectMenuBuilderを最新版のStringSelectMenueBuilderに書き換え
  botmain.js
  commands/createchan.js
Labels: bug

#23 Develop Update
  botmain.js
  commands/createchan.js
  commands/general.js
  functions/genshin.js
  functions/ryoshoku.js
  package.json
Labels: duplicate

#24 Feature/secretmsg
  commands/general.js
Labels: 定例アップデート, feature

#27 createChannel機能で確認されたバグの修正
  botmain.js
  commands/createchan.js
Labels: bug

#26 /secretmsg機能追加
  commands/general.js
Labels: 定例アップデート, feature

#31 v4.0.0 Release Candidate 2
  botmain.js
  commands/general.js
Labels: bug, Release Candidate

#33 v4.0.0 Release Candidate 3
  commands/general.js
Labels: bug, Release Candidate

#28 v4.0.0リリース
  README.md
  botmain.js
  commands/createchan.js
  commands/dashboard.js
  commands/general.js
  commands/genshinTimer.js
  commands/timeTable.js
  functions/dashboard.js
  package.json
Labels: bug, major update, feature

#50 secret-msgで文字数オーバーとファイルサイズオーバーでエラーになるバグを修正
  commands/general.js
Labels: bug, Emergency

#51 V4.0.1 Release
  commands/dashboard.js
  commands/general.js
  package.json
Labels: bug, patch update, Emergency

#56 Hotfix/23 4 6 secretmsg permissions2
  commands/general.js
  package.json
Labels: bug, patch update, Emergency

#58 Emergency/secretmsg timestamp
  commands/general.js
  package.json
Labels: bug, patch update, Emergency

#59 \\が\になるバグを修正
  commands/general.js
Labels: bug, patch update
