Repository NITKC-DEV/Kisarazu-Multi-Manager, pull requests merged in 2023-07, with the labels that each got.

#156 fixed "statusData is not defined"
  functions/statusAndMode.js
Labels: bug, Emergency

#167 CreateChannelのロール作成権限を上書きできるようにした
  commands/CreateChannel.js
Labels: feature, minor update

#164 君は完璧で究極のhelp
  botmain.js
  commands/general.js
  functions/help.js
  functions/helpText.json
Labels: feature, minor update

#170 #133 メンテナンスモード前後にCreateChannelの整合性検証を挟むようにした
  commands/general.js
Labels: feature, patch update

#166 僕は時間割をより良くしています。AC JAPANも支援してくれそうです(適当)
  commands/timeTable.js
  functions/ttGeneration.js
Labels: patch update, problem

#168 天気を良くした
  functions/dashboard.js
  functions/weather.js
Labels: patch update, problem

#169 Feature/secret message/#103
  commands/general.js
Labels: feature

#173 Create function AutoDeleteEditReply
  commands/general.js
  functions/common.js
Labels: feature, minor update

#176 スラッシュコマンド改善など
  commands/dashboard.js
  commands/general.js
  commands/timeTable.js
  functions/dashboard.js
Labels: minor update, patch update, problem

#179 ロールIDに直すの忘れてたらしい
  functions/CCFunc.js
Labels: problem

#177 ちょっとだけいい感じにした
  commands/general.js
  functions/common.js
Labels: feature

#183 BUGFIX TIME
  botmain.js
  functions/logsystem.js
  functions/weather.js
Labels: patch update, problem

#184 V5.0.0 docs
  .github/ISSUE_TEMPLATE/bug_report.yaml
  README.md
  botmain.js
  commands/general.js
  functions/helpText.json
  package.json
Labels: documentation, patch update

#187 v5.0.0 Release Candidate 1
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .gitignore
  .run/cmd-prod.run.xml
  .run/cmd.run.xml
  .run/dev.run.xml
  .run/start.run.xml
  CCConfigTemp.json
  README.md
  Templates/config.temp.json
  announcement.js
  botmain.js
  commands/CreateChannel.js
  commands/createchan.js
  commands/dashboard.js
  commands/general.js
  commands/genshinTimer.js
  commands/guildData.js
  commands/timeTable.js
  ecosystem.config.cjs
  functions/CCFunc.js
  functions/birthday.js
  functions/common.js
  functions/dashboard.js
  functions/db.js
  functions/genshin.js
  functions/guildDataSet.js
  functions/help.js
  functions/helpText.json
  functions/logsystem.js
  functions/statusAndMode.js
  functions/ttGeneration.js
  functions/weather.js
  package.json
  timetable/timetableUtils.js
Labels: bug, documentation, major update, feature, minor update, Release Candidate, patch update

#190 v5.0.0 RC2適用
  README.md
  botmain.js
  commands/guildData.js
  functions/guildDataSet.js
  functions/helpText.json
Labels: documentation, patch update

#198 V5.0.0 Release Candidata 3
  commands/general.js
Labels: patch update, problem

#199 v5.0.0 RC4適用
  botmain.js
Labels: patch update, problem

#202 v5.0.0 Release Candidate 5
  botmain.js
  functions/dashboard.js
  functions/weather.js
Labels: patch update, problem

#205 Problem/#204 rc6
  README.md
Labels: problem

#210 v5.0.0 Release Candidata 8
  commands/timeTable.js
Labels: Release Candidate, problem

#203 v5.0.0 Release
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .gitignore
  .run/cmd-prod.run.xml
  .run/cmd.run.xml
  .run/dev.run.xml
  .run/start.run.xml
  CCConfigTemp.json
  README.md
  Templates/config.temp.json
  announcement.js
  botmain.js
  commands/CreateChannel.js
  commands/createchan.js
  commands/dashboard.js
  commands/general.js
  commands/genshinTimer.js
  commands/guildData.js
  commands/timeTable.js
  ecosystem.config.cjs
  functions/CCFunc.js
  functions/birthday.js
  functions/common.js
  functions/dashboard.js
  functions/db.js
  functions/genshin.js
  functions/guildDataSet.js
  functions/help.js
  functions/helpText.json
  functions/logsystem.js
  functions/statusAndMode.js
  functions/ttGeneration.js
  functions/weather.js
  package.json
  timetable/timetableUtils.js
Labels: bug, documentation, major update, feature

#212 /guildDataがうまく動かない問題を修正
  commands/guildData.js
Labels: bug, Emergency

#213 修正パッチdevelop適用
  commands/guildData.js
Labels: bug, Emergency

#222 v5.0.1 Release
  botmain.js
  commands/timeTable.js
  package.json
Labels: bug, patch update, Fatal

#226 BOT起動時にguildの整合性を確認するよう変更
  botmain.js
Labels: patch update

#227 8弦目の終了時刻を修正
  functions/ttGeneration.js
Labels: documentation, patch update

#225 hotfix/SecretMessage #224
  commands/general.js
  package.json
Labels: bug, patch update

#228 v5.0.2適用
  botmain.js
  commands/general.js
  functions/ttGeneration.js
  package.json
Labels: Apply

#233 v5.0.3
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .run/dev.run.xml
  commands/timeTable.js
  functions/ttGeneration.js
  package.json
Labels: Bug, Documentation, Patch update
