Repository NITKC-DEV/Kisarazu-Multi-Manager, pull requests merged in 2023-06, with the labels that each got.

#64 ダッシュボードアプデ第2段
  README.md
  botmain.js
  commands/dashboard.js
  functions/dashboard.js
  functions/db.js
  functions/logsystem.js
Labels: bug, major update, feature

#74 Maintenance mode is ready
  Templates/CCConfigTemp.json
  Templates/config.temp.json
  botmain.js
  commands/dashboard.js
  commands/general.js
  commands/guildData.js
  functions/logsystem.js
Labels: major update

#85 天気機能v2
  botmain.js
  commands/dashboard.js
  commands/general.js
  commands/timeTable.js
  functions/dashboard.js
  functions/guildDataSet.js
  functions/logsystem.js
  functions/weather.js
Labels: feature, minor update

#89 Issue #81 & #87 等を修正
  commands/dashboard.js
  functions/dashboard.js
  functions/guildDataSet.js
Labels: bug, patch update

#94 IntelliJ系のエディタ用実行構成の作成
  .run/cmd-prod.run.xml
  .run/cmd.run.xml
  .run/dev.run.xml
  .run/start.run.xml
  botmain.js
  package.json
Labels: feature, patch update

#96 createChanをサーバー限定にする
  commands/createchan.js
Labels: bug, patch update

#119 timetable v2
  .gitignore
  announcement.js
  botmain.js
  commands/dashboard.js
  commands/timeTable.js
  functions/dashboard.js
  functions/db.js
  functions/logsystem.js
  functions/ttGeneration.js
  timetable/timetableUtils.js
Labels: major update, feature

#131 v4.0.7
  botmain.js
  commands/dashboard.js
  commands/general.js
  commands/genshinTimer.js
  package.json
  timetable/timetableUtils.js
Labels: patch update

#148 bot-statusとメンテナンスに関するアプデ
  botmain.js
  commands/dashboard.js
  commands/general.js
  functions/statusAndMode.js
  package.json
Labels: bug, feature, minor update

#153 𝑈𝐿𝑇𝐼𝑀𝐴𝑇𝐸 𝐼𝑀𝑃𝑅𝑂𝑉𝐸𝑀𝐸𝑁𝑇 𝑇𝐼𝑀𝐸
  botmain.js
  commands/general.js
  commands/guildData.js
  functions/weather.js
Labels: bug, feature, patch update

#152 nextTestの息の根を止めるプルリク
  commands/dashboard.js
  functions/dashboard.js
Labels: bug, patch update

#147 fixed weather-switcher & timetable
  commands/general.js
  commands/guildData.js
  commands/timeTable.js
  functions/dashboard.js
  functions/ttGeneration.js
  functions/weather.js
Labels: bug, patch update, Emergency
